Added appBar
ABOLYR/surf-flutter-course-Evstigneev pull request #6
Opened 2021-03-22 19:57 UTC by ABOLYR

2021-03-22 19:59 UTC, ABOLYR commented
![photo5388831768087475613](https://user-images.githubusercontent.com/34375522/112050668-2e03f800-8b62-11eb-91a6-c03f870bdc15.jpg)

2021-03-23 16:42 UTC, artem-zaitsev requested changes

2021-03-23 16:42 UTC, artem-zaitsev commented on lib/ui/screen/sight_list_screen.dart
> +                fontStyle: FontStyle.normal,
Наверное заметили, что в приложении явно не normal отображается?

Это связанос тем, что в пабспеке у вас прописано лишь одно начертание, и вне зависимости от указания здесь fontStyle/weight оно всегда будет одно.

Вернитесь в пабспек и подключите верные шрифты. и. Укажите им вес
https://flutter.dev/docs/cookbook/design/fonts#2-declare-the-font-in-the-pubspec

2021-03-24 17:42 UTC, artem-zaitsev approved these changes

2021-03-25 19:42 UTC, merged